channels:
- conda-forge
dependencies:
- python=3.12.4
- pip<=24.0
- pip:
  - mlflow==2.19.0
  - cloudpickle==3.1.0
  - numpy==2.0.0
  - psutil==6.1.1
  - scikit-learn==1.5.0
  - scipy==1.14.1
name: mlflow-env
